# options
# makes tmux not mess up colours 
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"
#add whatever this does
set-option -g focus-events on
# shortens time delay when escape is pressed
set-option -sg escape-time 0
# can use mouse 
set -g mouse on
# start window numbering at 1 
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
#set vi-mode
set-window-option -g mode-keys vi
#set clipboard 
set -s set-clipboard external

# Keymaps
# alt+H/L to move between windows
bind -n M-h previous-window
bind -n M-l next-window
#changes the prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
#changes copying in tmux buffers
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
#open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
#resize window
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
#fullscreen pane to be the same as window manager
bind -r m resize-pane -Z

# List of plugins
#plugin manager and some sensible tmux options
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#persistent tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-resurrect' 
#saves sessions every 15 minutes
set -g @plugin 'tmux-plugins/tmux-continuum'
# vim keys to navigate neovim and tmux
set -g @plugin 'christoomey/vim-tmux-navigator'

# presistenct tmux session setup
set -g @resurrect-capture-pane-content 'on'
set -g @continuum-restore 'on'

run '~/.config/tmux/.tmux/plugins/tpm/tpm'
